version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: omermunk
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: users_subjects_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: .
    depends_on:
      - db
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URL=postgresql://omermunk:1234@db:5432/users_subjects_db

volumes:
  db_data:
